project_id = "peqqefvohjemxhuyvzbg"

[functions.walletconnect-config]
verify_jwt = false

[functions.send-message-notification]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.submit-1inch-order]
verify_jwt = false

[functions.get-1inch-api-key]
verify_jwt = false

[functions.create-1inch-order]
verify_jwt = false

[functions.get-token-price]
verify_jwt = false

[functions.generate-kyc-token]
verify_jwt = true

[functions.sumsub-webhook]
verify_jwt = false

[functions.check-kyc-status]
verify_jwt = true

[functions.health-check]
verify_jwt = false

[functions.system-metrics]
verify_jwt = false